version: "3.9"

services:
  cache:
    image: redis:7-alpine
    environment:
      REDIS_PASSWORD: "s3cret_pwd"
    command: ["redis-server", "--requirepass", "s3cret_pwd"]
    deploy:
      restart_policy:
        condition: on-failure

  api:
    image: scd_web:latest
    environment:
      REDIS_HOST: cache
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "s3cret_pwd"
      WINDOW_SECONDS: "15"
      REQUESTS_KEY: "requests:win15"
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    depends_on:
      - cache
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
