version: "3.9"
services:
  redis:
    image: redis:7-alpine

  web:
    image: scd_web:latest
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      WINDOW_SECONDS: "10"
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    depends_on:
      - redis
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
